# Generated by Django 5.0.3 on 2024-03-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_published_date_post_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
